###wsdl
GET http://localhost:8080/calculatorService?wsdl
Accept: text/xml

###schema
GET http://localhost:8080/calculatorService?xsd=1
Accept: text/xml

###add
POST http://localhost:8080/calculatorService
Content-Type: text/xml

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                  xmlns:web="http://impl.service.soap.grigoryev.com/">
    <soapenv:Header/>
    <soapenv:Body>
        <web:add>
            <arg0>4</arg0>
            <arg1>3</arg1>
        </web:add>
    </soapenv:Body>
</soapenv:Envelope>

###sub
POST http://localhost:8080/calculatorService
Content-Type: text/xml

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                  xmlns:web="http://impl.service.soap.grigoryev.com/">
    <soapenv:Header/>
    <soapenv:Body>
        <web:sub>
            <arg0>5</arg0>
            <arg1>2</arg1>
        </web:sub>
    </soapenv:Body>
</soapenv:Envelope>
